blog/urls.py
from django.urls import path
from blog import views

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('post/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.CreatePostView.as_view(), name='post_new'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post_edit'),
    path('drafts/', views.DraftListView.as_view(), name='post_draft_list'),
    path('post/<int:pk>/publish/', views.post_publish, name='post_publish'),
    path('post/<int:pk>/remove/', views.PostDeleteView.as_view(), name='post_remove'),
    path('post/<int:pk>/comment/', views.post_comment, name='post_comment'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('category/<str:category>/', views.CategoryView.as_view(), name='category'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.IMAGE_URL, document_root=settings.IMAGE_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images',blank=True, null=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("post_detail", kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse("post_list")

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        # self.fields['title'].widget.attrs = {'placeholder': '必ずご入力ください。'}
        self.fields['author'].required = False
        self.fields['category'].required = False
        self.fields['title'].required = False
        self.fields['text'].required = False

    def clean_author(self):
        author = self.cleaned_data['author']
        if author == None:
            raise forms.ValidationError ('※投稿者をを選択してください。')
        return author

    def clean_category(self):
        category = self.cleaned_data['category']
        if category == None:
            raise forms.ValidationError ('※カテゴリを選択してください。')
        return category

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) == 0:
            raise forms.ValidationError ('※タイトルを入力してください。')
        return title

    def clean_text(self):
        text = self.cleaned_data['text']
        if len(text) == 0:
            raise forms.ValidationError ('※本文を入力してください。')
        return text

    class Meta:
        model = Post
        fields = ('author', 'category', 'title', 'text', 'image')

class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['author'].required = False
        self.fields['text'].required = False

    def clean_author(self):
        author = self.cleaned_data['author']
        if len(author) == 0:
            raise forms.ValidationError ('※名前を入力してください。')
        return author

    def clean_text(self):
        text = self.cleaned_data['text']
        if len(text) == 0:
            raise forms.ValidationError ('※本文を入力してください。')
        return text

    class Meta:
        model = Comment
        fields = ('author', 'text',)

accounts/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.utils import timezone
from blog.models import Post, Comment, Category
from blog.forms import PostForm, CommentForm
from django.urls import reverse_lazy
from django.views.generic import (TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

class PostListView(ListView):
    model = Post
    template_name = "blog/post_list.html"
    paginate_by = 3

    def get_queryset(self):
        # return Post.objects.all()
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model = Post
    template_name = "blog/post_detail.html"

class CreatePostView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    template_name = "blog/post_form.html"
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    template_name = "blog/post_form.html"
    redirect_field_name = 'blog/post_detail.html'
    form_class = PostForm
    model = Post

class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    template_name = 'blog/post_draft_list.html'
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')

class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = "blog/post_confirm_delete.html"
    success_url = reverse_lazy('post_list')

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('post_detail', pk=pk)

@login_required
def post_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blog/post_comment.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('post_detail', pk=comment.post.pk)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('post_detail', pk=comment.post.pk)

class AboutView(TemplateView):
    template_name = 'page/about.html'

class CategoryView(ListView):
    model = Post
    template_name = 'blog/post_list.html'

    def get_queryset(self):
        category = Category.objects.get(name=self.kwargs['category'])
        queryset = Post.objects.order_by('-id').filter(category=category)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_key'] = self.kwargs['category']
        return context

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Blog - Django Startup</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
	<link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/blog.css' %}" />
</head>

<body>
	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
		<div class="container">
		<a class="navbar-brand" href="/">Blog</a>
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
			data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
			aria-label="Toggle navigation">
			Menu
			<i class="fas fa-bars"></i>
		</button>
		<div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
				<li class="nav-item">
					<a class="nav-link" href="/">Home</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'about' %}">About</a>
				</li>
				{% if user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'post_new' %}">Post</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'post_draft_list' %}">Draft</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'account_logout' %}">Log out</a>
				</li>
				{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'account_login' %}">Login</a>
				</li>
				{% endif %}
			</ul>
		</div>
		</div>
	</nav>

	<!-- Page Header -->
	<header class="masthead">
		<div class="overlay"></div>
		<div class="container">
			<div class="row">
				<div class="col-lg-8 col-md-10 mx-auto">
					{% block header %}
					{% endblock %}
				</div>
			</div>
		</div>
	</header>

	<!-- Main Content -->
	<div class="container">
		<div class="row">
			{% block content %}
			{% endblock %}
		</div>
	</div>

	<hr>

	<!-- Footer -->
	<footer>
		<div class="container">
		<div class="row">
			<div class="col-lg-8 col-md-10 mx-auto">
			<ul class="list-inline text-center">
				<li class="list-inline-item">
				<a href="#">
					<span class="fa-stack fa-lg">
					<i class="fas fa-circle fa-stack-2x"></i>
					<i class="fab fa-github fa-stack-1x fa-inverse"></i>
					</span>
				</a>
				</li>
				<li class="list-inline-item">
				<a href="#">
					<span class="fa-stack fa-lg">
					<i class="fas fa-circle fa-stack-2x"></i>
					<i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
					</span>
				</a>
				</li>
				<li class="list-inline-item">
				<a href="#">
					<span class="fa-stack fa-lg">
					<i class="fas fa-circle fa-stack-2x"></i>
					<i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
					</span>
				</a>
				</li>
			</ul>
			<p class="copyright text-muted">Copyright &copy; 2020 TOMIZAWA Jun</p>
			</div>
		</div>
		</div>
	</footer>

	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
	<script src="{% static 'js/blog.js' %}"></script>

</body>
</html>

blog/templates/blog/post_comment.html
{% extends 'blog/base.html' %}
{% load widget_tweaks %}

{% block header %}
<div class="site-heading">
  <h1>New comment</h1>
</div>
{% endblock %}

{% block content %}
<div class="col-12">
  <form method="POST" class="post-form">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    <div class="form-group row">
      <label for="{{ form.author.id_for_label }}" class="col-lg-2 mb-1">投稿者名</label>
      <div class="col-lg-3">
        {{ form.author|add_class:'form-control' }}
        {% for error in form.author.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    <div class="form-group row">
      <label for="{{ form.text.id_for_label }}" class="col-lg-2 mb-1">コメント本文</label>
      <div class="col-lg-10">
        {{ form.text|add_class:'form-control' }}
        {% for error in form.text.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="text-right">
      <button type="submit" class="save btn btn-success" role="button">
        <i class="fas fa-paper-plane fa-fw"></i>送信
      </button>
    </div>
  </form>
</div>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}

{% block header %}
<div class="site-heading">
  <h1>Post Delete</h1>
</div>
{% endblock %}

{% block content %}
<div class="col-12">
  <div class="row justify-content-center">
    <form method="post">
      {% csrf_token %}
      <div class="text-center">
        <p>{{ object }}を削除してもよろしいですか？</p>
        <p>
          <button type="submit" class="save btn btn-danger" role="button">
            <i class="fas fa-trash-alt" fa-fw></i>削除</button>
        </p>
      </div>
    </form>
  </div>
</div>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block header %}
<div class="post-heading">
  <h1>{{ post.title }}</h1>
  {% if post.published_date %}
    <span class="meta">{{ post.published_date }}</span>
  {% endif %}
</div>
{% endblock %}

{% block content %}
<div class="col-12">
  {% if not post.published_date %}
    <a class="btn btn-warning" href="{% url 'post_publish' pk=post.pk %}" role="button">
      <i class="fas fa-upload fa-fw"></i>公開
    </a>
  {% endif %}
  {% if user.is_authenticated %}
    <a class="btn btn-success" href="{% url 'post_edit' pk=post.pk %}" role="button">
      <i class="fas fa-edit fa-fw"></i>編集
    </a>
    <a class="btn btn-danger" href="{% url 'post_remove' pk=post.pk %}" role="button">
      <i class="fas fa-trash-alt" fa-fw></i>削除
    </a>
  {% endif %}

  {% if post.image %}
  <style>
    header.masthead {
      background-image: url('{{ post.image.url }}') !important;
      background-position: left !important;
    }
  </style>
  {% endif %}

  <p>
    {{ post.text|linebreaksbr }}
  </p>

  <hr>
  <p>
    <a class="btn btn-success" href="{% url 'post_comment' pk=post.pk %}" role="button">
      <i class="fas fa-edit fa-fw"></i>コメント追加
    </a>
  </p>
  {% for comment in post.comments.all %}
    {% if not comment.approved_comment %}
      <p>
        <a class="btn btn-danger" href="{% url 'comment_remove' pk=comment.pk %}" role="button">
          <i class="fas fa-trash-alt" fa-fw></i>コメント削除
        </a>
        <a class="btn btn-primary" href="{% url 'comment_approve' pk=comment.pk %}" role="button">
          <i class="fas fa-upload fa-fw"></i>コメント承認
        </a>
      </p>
    {% endif %}

    <p class="comment-meta m-0">{{ comment.created_date }}</p>
    <span>{{ comment.author }}</span>
    <p>{{ comment.text|linebreaks }}</p>

    {% empty %}
    <p>まだコメントはありません。</p>
  {% endfor %}
</div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}

{% block header %}
<div class="site-heading">
  <h1>Draft</h1>
</div>
{% endblock %}

{% block content %}
<div class="col-12">
  {% for post in post_list %}
  <div class="post-preview">
    <a href="{% url 'post_detail' pk=post.pk %}">
    <h2 class="post-title">
      {{ post.title }}
    </h2>
    </a>
    <p class="post-meta">{{ post.created_date }}</p>
    <p>{{ post.text|truncatechars:200 }}</p>
  </div>
  <hr>
  {% endfor %}
</div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load widget_tweaks %}

{% block header %}
<div class="site-heading">
  <h1>New post</h1>
</div>
{% endblock %}

{% block content %}
<div class="col-12">
  <form method="POST" class="post-form" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- {{ form.as_p }} -->
    <div class="form-group row">
      <label for="{{ form.author.id_for_label }}" class="col-lg-2 mb-1">投稿者</label>
      <div class="col-lg-3">
        {{ form.author|add_class:'form-control' }}
        {% for error in form.author.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    <div class="form-group row">
      <label for="{{ form.category.id_for_label }}" class="col-lg-2 mb-1">カテゴリ</label>
      <div class="col-lg-3">
        {{ form.category|add_class:'form-control' }}
        {% for error in form.category.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    <div class="form-group row">
      <label for="{{ form.title.id_for_label }}" class="col-lg-2 mb-1">タイトル</label>
      <div class="col-lg-10">
        {{ form.title|add_class:'form-control' }}
        {% for error in form.title.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    <div class="form-group row">
      <label for="{{ form.text.id_for_label }}" class="col-lg-2 mb-1">本文</label>
      <div class="col-lg-10">
        {{ form.text|add_class:'form-control' }}
        {% for error in form.text.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    <div class="form-group row">
      <label for="{{ form.image.id_for_label }}" class="col-lg-2 m-0">画像<span class="help-text">※任意</span></label>
      <div class="col-lg-10">
        {{ form.image|add_class:'form-control' }}
        {% for error in form.image.errors %}
          <span class="help-block">{{ error }}</span>
        {% endfor %}
      </div>
    </div>


    <div class="text-right">
      <button type="submit" class="save btn btn-success" role="button">
        <i class="fas fa-paper-plane fa-fw"></i>送信
      </button>
    </div>
  </form>
</div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block header %}
<div class="site-heading">
	<h1>Django Startup</h1>
	<span class="subheading">This is my first step!</span>
</div>
{% endblock %}

{% block content %}
<div class="col-12 col-md-9">
	{% for post in post_list %}
	<div class="post-preview">
		<a href="{% url 'post_detail' pk=post.pk %}">
			<h2 class="post-title">
				{{ post.title }}
			</h2>
		</a>
		<p class="post-meta">{{ post.published_date }}</p>
		<p>{{ post.text|linebreaksbr|truncatechars:100 }}</p>
		<a href="{% url 'post_detail' pk=post.pk %}">
			<p class="post-comment">コメント数: {{ post.approved_comments.count }}</p>
		</a>
	</div>
	<hr>
	{% endfor %}
	<ul class="pagination pagination-sm justify-content-center">
		{% if page_obj.has_previous %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.previous_page_number }}">
					<span aria-hidden="true">前</span>
				</a>
			</li>
		{% endif %}

		{% for num in page_obj.paginator.page_range %}
			{% if page_obj.number == num %}
				<li class="page-item active"><a class="page-link" href="#!">{{ num }}</a></li>
			{% else %}
				<li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
			{% endif %}
		{% endfor %}

		{% if page_obj.has_next %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.next_page_number }}">
					<span aria-hidden="true">次</span>
				</a>
			</li>
		{% endif %}
	</ul>
</div>
<div class="col-12 col-md-3">
	<h5>カテゴリ</h5>
	<div class="category">
		<ul>
			{% for category in category_list %}
			<a href="{% url 'category' category %}">
				<li>{{ category.name }}</li>
			</a>
			{% endfor %}
		</ul>
	</div>
</div>
{% endblock %}

blog/templates/page/about.html
{% extends 'blog/base.html' %}

{% block header %}
<div class="site-heading">
  <h1>About</h1>
</div>
{% endblock %}

{% block content %}
<div class="col-12">
  <p>Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space Free Space</p>
</div>
{% endblock %}